// Writes src/favorites/han-fold-table.ts from OpenCC's character tables: run it by hand to update.
import { join } from "node:path";

const OPENCC_COMMIT = "3ac34aa439a9908dd49fa92b5174b46314787ac2";
const OUT = join(import.meta.dir, "..", "src", "favorites", "han-fold-table.ts");

async function table(name: string): Promise<Map<string, string>> {
  const url = `https://raw.githubusercontent.com/BYVoid/OpenCC/${OPENCC_COMMIT}/data/dictionary/${name}.txt`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${name}: ${response.status}`);
  }
  const pairs = new Map<string, string>();
  for (const line of (await response.text()).split("\n")) {
    const [key, values] = line.split("\t");
    const first = values?.trim().split(" ")[0];
    // One UTF-16 unit for one: a search folds unit by unit and marks matches by position.
    if (key?.length === 1 && first?.length === 1) {
      pairs.set(key, first);
    }
  }
  return pairs;
}

const reversed = (pairs: Map<string, string>) =>
  new Map([...pairs].map(([standard, variant]) => [variant, standard]));

const shinjitai = await table("JPShinjitaiCharacters");
const variants = new Map([
  ...reversed(await table("TWVariants")),
  ...reversed(await table("HKVariants")),
]);
const simplified = await table("TSCharacters");

const folded = new Map<string, string>();
for (const char of new Set([...shinjitai.keys(), ...variants.keys(), ...simplified.keys()])) {
  const traditional = shinjitai.get(char) ?? char;
  const standard = variants.get(traditional) ?? traditional;
  const to = simplified.get(standard) ?? standard;
  if (to !== char) {
    folded.set(char, to);
  }
}

const from = [...folded.keys()].join("");
const to = [...folded.values()].join("");
await Bun.write(
  OUT,
  `// Generated by scripts/han-fold-table.ts from OpenCC ${OPENCC_COMMIT.slice(0, 7)}
// (https://github.com/BYVoid/OpenCC, Apache License 2.0). Do not edit.
export const HAN_FOLDED_FROM =
  ${JSON.stringify(from)};
export const HAN_FOLDED_TO =
  ${JSON.stringify(to)};
`,
);
console.log(`${folded.size} characters fold`);
