// The interface/platform contract. It imports no parser, so the Electron preload can use it.
export {
  type ArgumentCheck,
  isCostumeSet,
  isFavoriteSongState,
  isFolderState,
  isNameState,
  isPictureWant,
  isTitleState,
  isTitleTarget,
  isWhole,
  PORT_ARGUMENTS,
} from "./arguments";
export { BRIDGE_CHANNELS } from "./bridge-channels";
export { checkedPort } from "./checked-port";
export { changedTheCostume } from "./costume-changed";
export {
  PORT_QUEUEING,
  type PortImplementation,
  type VerbImplementation,
  type VerbQueueing,
  type VerbsQueued,
} from "./queueing";
export type {
  ChineseNamesRead,
  CostumeChange,
  CostumeEditorView,
  CostumeHistoryEntry,
  CostumePreviewFailure,
  CostumeSet,
  CostumeSlot,
  CourseIconWant,
  CrownKind,
  DanNumber,
  DanView,
  FavoriteSongChange,
  FavoriteSongEditorView,
  FavoriteSongState,
  FavoritesView,
  FolderChange,
  FolderEditorView,
  FolderState,
  HirobaSessionPort,
  IconWant,
  NameChange,
  NameState,
  OptionIconWant,
  PickableSongs,
  PictureFailure,
  PictureView,
  PictureWant,
  PipelinesView,
  ProfileView,
  ReadFailure,
  ReadFailureKind,
  ReadProfileOptions,
  RecentPlaysFailure,
  RenameState,
  ScoresFailure,
  ScoresProgress,
  ScoresStop,
  ScoresView,
  ScoreView,
  ShownSong,
  SignInOutcome,
  SongCatalogueFailure,
  SongCatalogueRead,
  TitleChange,
  TitleEditorView,
  TitleState,
  TitleTarget,
  UpdateFeed,
  UpdateFeedFailure,
  WriteKind,
  WriteOutcomeView,
  WriteSets,
} from "./types";
